import hero from '../assets/images/background/pattern-21.png';
import about from '../assets/images/resource/about-1.png';
import contact from '../assets/images/resource/contact.png';
import subscribe from '../assets/images/resource/subscribe.png';
import serviceImage from '../assets/images/resource/service.jpg';
import project1 from '../assets/images/gallery/1.jpg';
import project2 from '../assets/images/gallery/2.jpg';
import project3 from '../assets/images/gallery/3.jpg';
import project4 from '../assets/images/gallery/4.jpg';
import news1 from '../assets/images/resource/news-1.jpg';
import news2 from '../assets/images/resource/news-2.jpg';
import news3 from '../assets/images/resource/news-3.jpg';
import brand from '../brand';

const image = sourceUrl => ({ sourceUrl });
const sections = (...names) => ({ componentsSections: names.map(title => ({ __typename: 'Component', title })) });
const page = (id, title, content = '', ...names) => ({ __typename: 'Page', id, title, content, componentsSectionsAllPages: sections(...names) });
export const services = [
    ['web-design-develpment', 'Web Design & Development', 'Thoughtful design and fast, accessible websites built around your audience.'],
    ['digital-marketing', 'Digital Marketing', 'Focused campaigns that connect your business with the right people.'],
    ['ecommerce', 'Ecommerce', 'Simple shopping experiences that turn product discovery into confident purchases.'],
    ['seo-optimization', 'SEO Optimization', 'Useful content and strong technical foundations for better search visibility.'],
    ['hosting', 'Website Hosting', 'Reliable infrastructure and ongoing care for your website.'],
    ['development', 'Custom Development', 'Practical digital tools tailored to the way your business works.'],
].map(([slug, title, text], i) => ({ __typename: 'Service', id: `service-${i}`, title, uri: `/services/${slug}/`, excerpt: `<p>${text}</p>`, content: `<h2>${title} with a clear purpose</h2><p>${text}</p><p>We start by understanding your goals, plan the right approach, and work with you from the first idea through launch and ongoing improvement.</p><h3>What you can expect</h3><ul><li>A clear project plan and regular updates</li><li>Careful attention to usability and performance</li><li>Support as your business grows</li></ul>`, featuredImage: { node: { id: `service-image-${i}`, ...image(serviceImage) } } }));
export const projectCategories = ['Web Design', 'Ecommerce'].map((name, i) => ({ id: `project-category-${i}`, name, uri: `/project_cat/${i ? 'ecommerce' : 'web-design'}/` }));
export const projects = ['Studio North', 'Everyday Goods', 'Fieldwork Collective', 'Modern Living'].map((title, i) => ({ __typename: 'Project', id: `project-${i + 1}`, title, uri: `/projects/project-${i + 1}/`, content: `<h2>A fresh digital experience for ${title}</h2><p>This fictional project shows how strategy, visual design, and development come together in an easy-to-use website.</p><p>We simplified the content, created a consistent visual language, and designed clear journeys across mobile and desktop.</p>`, projectCategories: { nodes: [projectCategories[i % 2]] }, projectExtraFields: { listThumb: image([project1, project2, project3, project4][i]), mainImage: image([project1, project2, project3, project4][i]), secondImage: null, projectInfo: `<ul><li>Client: ${title} (demo)</li><li>Services: Design and development</li><li>Project: Concept showcase</li></ul>` } }));
export const categories = [{ id: 'category-1', name: 'Insights', uri: '/category/insights/', count: 8 }];
export const tags = [{ id: 'tag-1', name: 'Strategy', uri: '/tag/strategy/' }];
export const posts = ['Planning a Better Website', 'Designing for Your Customers', 'A Practical Guide to Ecommerce', 'Content That Helps People', 'Making Your Website Faster', 'Building a Consistent Brand', 'Measuring What Matters', 'Preparing for Launch'].map((title, i) => ({ __typename: 'Post', id: `post-${i}`, databaseId: i + 1, title, uri: `/insight-${i + 1}/`, excerpt: `<p>Practical ideas for your next digital project: ${title.toLowerCase()}.</p>`, content: `<h2>${title}</h2><p>Start with the people who will use your website. Understand what they need, remove unnecessary steps, and make the next action clear.</p><h3>Start small and learn</h3><p>Choose a specific goal, create a simple plan, and review the results. A useful digital experience improves over time through feedback and thoughtful iteration.</p><p>This is sample editorial content for the Digital Agency theme.</p>`, featuredImage: { node: { id: `post-image-${i}`, ...image([news1, news2, news3][i % 3]) } }, postExtraFields: { mainImage: image([news1, news2, news3][i % 3]) }, categories: { edges: categories.map(node => ({ node })) }, tags: { edges: tags.map(node => ({ node })) } }));
export const pages = {
    homepage: { ...page('home', 'Home', '', 'SectionOurServices', 'SectionAboutUs', 'SectionWhyUs', 'SectionTestimonials', 'SectionFAQ', 'SectionSubscribeToNL'), homepageFields: { heroImage: image(hero), heroImageOverlay: image(about), heroTitle: 'Digital experiences that move your business forward.', heroSubTitle: 'Strategy, design, and technology for ambitious brands. Let’s build something your customers will love.', heroButtonText: 'Explore our work', heroButtonUrl: '/portfolio/' } },
    about: page('about', 'About Us', '<p>We are a collaborative digital agency bringing together strategy, design, and development. We help businesses turn their ideas into useful digital experiences.</p>', 'SectionAboutUs', 'SectionWhyUs'),
    'about/testimonials': page('testimonials', 'Testimonials', '', 'SectionTestimonials'),
    services: page('services', 'Our Services', '', 'SectionOurServices', 'SectionWhyUs'),
    faq: page('faq', 'Frequently Asked Questions', '', 'SectionFAQ'),
    blog: page('blog', 'Insights & Ideas', '', 'SectionBlog'),
    contact: { ...page('contact', 'Contact'), contactFields: { smallTitleTop: 'LET’S TALK', mainTitle: 'Tell us about your next project', secondaryTitle: 'Good work starts with a conversation', secondaryText: 'Share your goals and explore what we could create together.', embedMapCode: '<div style="padding:60px;background:#eef6fc;border-radius:12px"><h3>Let’s connect</h3><p>We collaborate remotely with teams everywhere.</p><p>Demo agency — location details can be customized.</p></div>', contactImage: image(contact), contactTitle: 'Digital Agency', contactAddress: 'Your city, your country', contactAddressLink: '/contact/', contactPhone1: '+1 202 555 0100', contactPhone2: '+1 202 555 0101', contactEmail: brand.email } },
};
const box = (title, text, link = '/contact/') => ({ boxIconClass: 'fa fa-lightbulb-o', boxTitle: title, boxText: text, boxLink: link });
export const components = {
    sectionourservices: { sectionOurServicesFields: { smallTitleTop: 'WHAT WE DO', mainTitle: 'Everything your digital presence needs', ...Object.fromEntries(services.slice(0, 5).map((s, i) => [`box${i + 1}`, box(s.title, s.excerpt.replace(/<[^>]*>/g, ''), s.uri)])) } },
    sectionaboutus: { sectionAboutUsFields: { smallTitleTop: 'MEET YOUR DIGITAL PARTNER', mainTitle: 'Creative thinking. Practical results.', mainText: '<p>We bring curious minds and complementary skills to every project. From the first conversation to launch day, we keep the process clear and collaborative.</p>', personName: 'Alex Morgan', personTitle: 'Creative Director · Demo team', personImage: image(about), mainImage: image(about) } },
    sectionwhyus: { sectionWhyUsFields: { smallTitleTop: 'WHY WORK WITH US', mainTitle: 'A team invested in your next step', mainSubTitle: 'We connect business goals with thoughtful digital experiences.', featuresTitle: 'A clear process from start to finish', features: 'Strategy before execution\nDesign with your customers in mind\nOpen communication at every stage\nSupport beyond launch', featuresButtonText: 'Start a conversation', featuresButtonLink: '/contact/', box1: box('Understand', 'We listen, research, and define what success looks like.'), box2: box('Create', 'We turn a shared direction into clear, useful experiences.'), box3: box('Improve', 'We test, learn, and refine as your business grows.') } },
    sectionsubscribetonl: { sectionSubscribeToNLFields: { mainImage: image(subscribe), mainTitle: 'Fresh ideas for your digital journey' } },
    sectiontestimonials: { sectionTestimonialsFields: { smallTitleTop: 'SAMPLE CLIENT STORIES', mainTitle: 'Great work starts with great partnerships', testimonialCases: ['Jamie Taylor', 'Sam Rivera'].map((title, i) => ({ __typename: 'Testimonial', id: `testimonial-${i}`, title, excerpt: '<p>Fictional client · Demo testimonial</p>', content: `<p>${i ? 'A thoughtful team that made a complex project feel manageable from day one.' : 'The process was clear, collaborative, and focused on what our customers actually needed.'}</p>`, featuredImage: { node: { id: `author-${i}`, ...image(about) } } })) } },
    sectionfaq: { sectionFaqFields: { smallTitleTop: 'YOUR QUESTIONS, ANSWERED', mainTitle: 'A little clarity before we start', mainText: 'Every project is different. Here are a few things that help us get started.', buttonLink: '/contact/', buttonText: 'Ask us a question', faqCases: [['How does a project begin?', 'We start with a conversation about your audience, goals, timeline, and budget.'], ['How long does a website take?', 'The timeline depends on scope and content. We agree on milestones together before work begins.'], ['Can you support us after launch?', 'Yes. Ongoing improvements, content updates, and technical care can be part of the plan.']].map(([title, text], i) => ({ __typename: 'FAQ', id: `faq-${i}`, title, content: `<p>${text}</p>` })) } },
};
Object.entries(components).forEach(([id, value]) => Object.assign(value, { __typename: 'Component', id, title: id }));
const route = (uri, label, reactComponent = 'TemplatePage') => ({ id: `route-${uri}`, uri, label, menuExtraFieldsForSitemap: { reactComponent, seoTitle: `${label} | ${brand.name}`, seoDescription: brand.description, seoCanonical: null } });
export const routes = [route('/about/', 'About'), route('/services/', 'Services'), route('/portfolio/', 'Portfolio', 'PagePortfolio'), route('/blog/', 'Blog'), route('/contact/', 'Contact', 'PageContact'), route('/faq/', 'FAQ'), route('/about/testimonials/', 'Testimonials'), ...services.map(s => route(s.uri, s.title, 'TemplateServiceInner')), route('/projects/:slug/', 'Project', 'TemplatePortfolioInner'), route('/blog/:slug/', 'Article', 'TemplateBlogInner'), route('/category/insights/', 'Insights', 'TemplateTaxonomy'), route('/tag/strategy/', 'Strategy', 'TemplateTaxonomy'), route('/search/:slug/', 'Search', 'TemplateTaxonomy')];
export const primaryMenu = [route('/', 'Home'), ...routes.slice(0, 5)].map((r, i) => ({ ...r, databaseId: i + 1, parentDatabaseId: 0, childItems: { nodes: [] } }));
